display-name: Thunder Web Runtime - JavaScript
team-name: Thunder Web Runtime - JS
core-deploy:
    enabled: true
    project-modules:
        ui-twr-modules: ui-twr-modules.version
    use-core-packager: true
steps:
  npm-configure:
    params:
      registry-url: https://registry.yarnpkg.com
      npmPublicToken: "{{ secrets.NPM_TOKEN }}"
  npm-configure-for-publish:
    params:
      registry-url: https://registry.npmjs.org
      npmPublicToken: "{{ secrets.NPM_TOKEN }}"
  npm-configure-for-update: 
    params:
      registry-url: https://registry.yarnpkg.com
      npmPublicToken: "{{ secrets.NPM_TOKEN }}"
branches:
  release:
    description: npm release only branch
    pull-request:
      workflow: release
  rel/0.0.x:
    description: npm release only branch
    pull-request:
      workflow: release
