display-name: Thunder Web Runtime - JavaScript
team-name: Thunder Web Runtime - JS
steps:
  node-install: &node-install
    group: build
    type: node-command
    description: install dependencies
    node:
      command: install
      default: true
    retry-times: 2
    env:
      NPM_TOKEN: "{{ secrets.NPM_TOKEN }}"
