display-name: Thunder Web Runtime - JavaScript
team-name: Thunder Web Runtime - JS
steps:
    node-build:
        group: build
        description: run build with private scope npm token
        run:
            command: "yarn build"
        env:
            NPM_TOKEN: "{{ secrets.NPM_TOKEN }}"
