display-name: Thunder Web Runtime - JavaScript
team-name: Thunder Web Runtime - JS
steps:
  node-install:
    group: build
    description: install dependencies with private scope npm token
    run:
      command: "yarn install"
    env:
        NPM_TOKEN: "{{ secrets.NPM_TOKEN }}"